# Generated by Django 6.0 on 2026-04-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvantageCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon_svg', models.TextField(verbose_name='SVG иконка (код)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Карточка преимущества',
                'verbose_name_plural': 'Карточки преимуществ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PriceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('price_display', models.CharField(max_length=100, verbose_name='Цена (текст)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('button_text', models.CharField(default='Заказать', max_length=50, verbose_name='Текст кнопки')),
                ('is_highlighted', models.BooleanField(default=False, verbose_name='Выделенная карточка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Ценовая карточка',
                'verbose_name_plural': 'Ценовые карточки',
                'ordering': ['order'],
            },
        ),
    ]
