# Generated by Django 6.0 on 2026-04-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricecard',
            name='card_type',
            field=models.CharField(choices=[('wide', 'Широкая'), ('thin', 'Тонкая')], default='thin', max_length=10, verbose_name='Тип карточки'),
        ),
    ]
