# Generated by Django 6.0 on 2026-04-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pricecard_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricecard',
            name='icon_svg',
            field=models.TextField(blank=True, null=True, verbose_name='SVG иконка (код)'),
        ),
    ]
