# Generated by Django 6.0 on 2026-06-09 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pricecard_icon_svg'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardAccordionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок пункта')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accordion_items', to='core.pricecard', verbose_name='Карточка')),
            ],
            options={
                'verbose_name': 'Пункт аккордеона',
                'verbose_name_plural': 'Пункты аккордеона',
                'ordering': ['order'],
            },
        ),
    ]
