# Generated by Django 6.0 on 2026-06-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cardaccordionitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudiencePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='URL (slug)')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=400, verbose_name='Подзаголовок')),
                ('content', models.TextField(blank=True, verbose_name='Основной текст')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='Meta description (SEO)')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликована')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в меню')),
            ],
            options={
                'verbose_name': 'Страница аудитории',
                'verbose_name_plural': 'Страницы аудиторий',
                'ordering': ['order'],
            },
        ),
    ]
