# Generated by Django 6.0 on 2026-06-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_audience_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('offer', 'Договор оферты'), ('privacy', 'Политика конфиденциальности'), ('consent', 'Согласие на обработку данных'), ('terms', 'Пользовательское соглашение')], max_length=20, unique=True, verbose_name='Тип документа')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержимое (HTML)')),
            ],
            options={
                'verbose_name': 'Страница документа',
                'verbose_name_plural': 'Страницы документов',
            },
        ),
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ (HTML)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'FAQ — вопрос',
                'verbose_name_plural': 'FAQ — вопросы',
                'ordering': ['order'],
            },
        ),
    ]
