# Generated by Django 6.0.4 on 2026-06-10 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_infopage_infocard'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricecard',
            name='detail_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.infopage', verbose_name='Страница подробнее'),
        ),
    ]
