# Generated by Django 6.0.4 on 2026-06-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_pricecard_detail_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopage',
            name='badge_text',
            field=models.CharField(blank=True, default='Комплексное решение', max_length=100, verbose_name='Текст бейджа'),
        ),
        migrations.AddField(
            model_name='infopage',
            name='cta_text',
            field=models.CharField(blank=True, default='Первая консультация 15 минут — бесплатно. Разберём вашу ситуацию и предложим оптимальное решение.', max_length=400, verbose_name='Текст CTA'),
        ),
        migrations.AddField(
            model_name='infopage',
            name='cta_title',
            field=models.CharField(blank=True, default='Готовы начать?', max_length=200, verbose_name='Заголовок CTA'),
        ),
        migrations.AddField(
            model_name='infopage',
            name='price_display',
            field=models.CharField(blank=True, max_length=100, verbose_name='Цена (текст)'),
        ),
        migrations.AddField(
            model_name='infopage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок'),
        ),
    ]
