# Generated by Django 6.0.4 on 2026-06-10 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_infopage_badge_text_infopage_cta_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infocard',
            name='audience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.audiencepage', verbose_name='Страница аудитории'),
        ),
        migrations.AddField(
            model_name='pricecard',
            name='audience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.audiencepage', verbose_name='Страница аудитории'),
        ),
    ]
