# Generated by Django 6.0 on 2026-04-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Логотип')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото в Hero-секции')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото в блоке Обо мне')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
